name: Deploy GitHub Pages
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Inject secret into JavaScript file
              run: echo "const API_KEY = '${{ secrets.HELIOS }}';" > secret.js

            - name: Deploy to GitHub Pages
              uses: actions/upload-pages-artifact@v2
